version: '3'
services:
  proto:
    command: ./scripts/protoc.sh
    build:
      context: ./
      dockerfile: ./DockerfileProto
    volumes:
      - .:/proto
  server:
    command: ./scripts/server.sh
    build:
      context: ./
      dockerfile: ./DockerfileGo
    volumes:
      - .:/go/src/grpc-web-react-hooks
    ports:
      - "9090:9090"
    depends_on:
      - proto
